"use client";
import "@/styles/globals.css";
import { Inter } from "next/font/google";

import QueryProviders from "./react-query-provider";
import Image from "next/image";
import Footer from "@/components/EngagementPrediction/Footer";
import {
	DropdownEmployee,
	DropdownHCDashBoard,
	DropdownManPower,
	DropdownUserManagament,
} from "@/components/Other/DropDown";
import { CaretDownFilled } from "@ant-design/icons";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
	title: "IR Portal",
	description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: JSX.Element }) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<nav className="shadow-bottom flex justify-between bg-white px-10 py-5 shadow-md">
					<div className="flex items-center gap-10">
						<strong className="text-xl">Logo</strong>
						<DropdownHCDashBoard
							label1="EES"
							label2="MPS"
							tittle="HC Dashboard"
							iconRight={
								<CaretDownFilled
									style={{
										color: "blue",
										alignItems: "center",
										padding: "1px",
									}}
								/>
							}
							dropRight1="EES DashBoard"
							dropRight2="Benchmark Dashboard"
							dropRight3="Prediction Dashboard"
							dropRight4="Detail Respondent Answear"
							dropRight5="Survey Progress Monitoring"
							dropRight6="Executive Summary"
							dropRight7="Executive Summary-Summary Table"
							dropRight8="Sustainability Overview"
							dropRight9="Demography Analysis"
							dropRight10="Comparison "
							dropRight11="Manpower Trend"
							dropRight12="Recruitment & Training"
							dropRightRight1="Survey Progress Monitoring Open"
							dropRightRight2="Survey Progress Monitoring Close"
						></DropdownHCDashBoard>
						<DropdownEmployee
							label1="Cleansing Survey"
							label2="Edit Wordcloud"
							label3="Invited Respondent SPM"
							label4="Master Data EES"
							tittle="Portal Employee Engagement Survey"
							iconRight={
								<CaretDownFilled
									style={{
										color: "blue",
										alignItems: "center",
										padding: "1px",
									}}
								/>
							}
							dropRight1="Download"
							dropRight2="Upload "
							dropRight3="Monitoring"
							dropRight4="Complete"
							dropRight5="Workcloud"
							dropRight6="Ngram"
							dropRight7="Upload Invited Respondent"
							dropRight8="Modify Data Invited Respondent"
							dropRight9="Maintain Demography"
							dropRight10="Maintain Master Data"
							dropRight11="Maintain Demography"
							urlRight1="./cleansing-survey/download/"
							urlRight2="./cleansing-survey/upload/"
							urlRight3="./cleansing-survey/monitoring/"
							urlRight4="./cleansing-survey/complete/"
							urlRight5="./edit-wordcloud/stopword-replace-wordcloud"
							urlRight6="./edit-wordcloud/ngram"
							urlRight7="./survey-progress-monitoring/upload-invited-respondent"
							urlRight8="./survey-progress-monitoring/modify-data-invited-respondent"
							urlRight9="./survey-progress-monitoring/maintain-demography"
							urlRight10="./ees/master-company-ees/"
							urlRight11="./ees/master-business-line-ees/"
							url1="/"
							url2="/"
							url3="/"
							url4="/"
						></DropdownEmployee>
						<DropdownManPower
							label1="Input MPS"
							label2="Master Data MPS"
							tittle="Portal Manpower Statis"
							iconRight={
								<CaretDownFilled
									style={{
										color: "blue",
										alignItems: "center",
										padding: "1px",
									}}
								/>
							}
							dropRight1="Upload MPS"
							dropRight2="Maintain Data"
							dropRight3="Maintain Master Data"
							dropRight4="Maintain Demography"
							urlRight1="./man-power-statistik/upload-mps"
							urlRight2="./man-power-statistik/maintain-mps"
							urlRight3="/mps/master-company-mps/"
							urlRight4="./mps/master-business-line-mps/"
						></DropdownManPower>
						<DropdownUserManagament
							label1="Master User"
							label2="Master Menu"
							tittle="User Management"
							iconRight={
								<CaretDownFilled
									style={{
										color: "blue",
										alignItems: "center",
										padding: "1px",
									}}
								/>
							}
							dropRight1="Maintain User"
							dropRight2="Maintain Role "
							dropRight3="Mapping User Role"
							dropRight4="Manage Access to Company"
							dropRight5="Maintain HC Dashboard"
							dropRight6="Maintain Menu"
							dropRight7="Manage Portal Access"
							urlRight1="./master-user/maintain-user/"
							urlRight2="./master-user/maintain-role/"
							urlRight3="./master-user/mapping-user-role/"
							urlRight4="./master-user/manage-access-to-company/"
							urlRight5="./master-menu/maintain-hc-dashboard/"
							urlRight6="./master-menu/maintain-menu/"
							urlRight7="./master-menu/manage-portal-access/"
						></DropdownUserManagament>
					</div>
					<div className="flex items-center ">
						<Image src="/propic.png" alt="profile_pic" height={25} width={25} />
					</div>
				</nav>
				<div className="bg-gray-100">{children}</div>
				<Footer />
			</body>
		</html>
	);
}
